"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['init.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'images/icon.icns',
    'packages': ['requests']
}

setup(
    name='Gumpy',
    version='1.0',
    app=APP,
    data_files=DATA_FILES,
    include_package_data=True,
    options={'py2app': OPTIONS},
    setup_requires=['py2app', 'mechanicalsoup', 'rumps']
)